# Generated by Django 4.0.3 on 2022-03-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='module_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='moduleinstance',
            old_name='moduleInstance_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='moduleinstance',
            old_name='moduleInstance_code',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='moduleinstance',
            old_name='moduleInstance_professor',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='moduleinstance',
            old_name='moduleInstance_semester',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='moduleinstance',
            old_name='moduleInstance_year',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='professor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='professor_name',
            new_name='name',
        ),
    ]
